#!/bin/bash
echo "========= Start setup ========"

echo "========= Start configurenek ========"
# TODO: very basic...
# ma2,map
configurenek --FC mpif77 $1 $2
# co2 without DPROCMAP
#configurenek --FC mpif77 --extra-FFLAGS ' -DPARRSB -DPARMETIS' --extra-CFLAGS '-DPARRSB -DPARMETIS' $1 $2 
# co2 with DPROCMAP:
#configurenek --FC mpif77 --extra-FFLAGS ' -DPROCMAP -DPARRSB -DPARMETIS' --extra-CFLAGS '-DPROCMAP -DPARRSB -DPARMETIS' $1 $2

echo "======== Make User file ========"

CASENAME=$2
export CASENAME
./mkuserfile

echo "========= Complete ========"
