#!/bin/bash
echo "========= Start setup ========"

echo "========= Compile 3rd party ========"
# set defaults # TODO: hardcoded, ignore flags in compilation for now....
CASEDIR=`pwd`
CASENAME=$2
export CASENAME
: ${NEKCEM_SOURCE_ROOT:="/usr/local/NekCEM"}
: ${FC:="mpif77"}
: ${CC:="mpicc"}
SOURCE_ROOT_BLAS="$NEKCEM_SOURCE_ROOT/3rd_party/blasLapack"
export SOURCE_ROOT_BLAS
SOURCE_ROOT_GSLIB="$NEKCEM_SOURCE_ROOT/3rd_party/gslib"
export SOURCE_ROOT_GSLIB
SOURCE_ROOT_PARRSB="$NEKCEM_SOURCE_ROOT/3rd_party/parRSB"
export SOURCE_ROOT_PARRSB
SOURCE_ROOT_PARMETIS="$NEKCEM_SOURCE_ROOT/3rd_party/parMETIS"
export SOURCE_ROOT_PARMETIS
SOURCE_ROOT_CVODE="$NEKCEM_SOURCE_ROOT/3rd_party/cvode"
export SOURCE_ROOT_CVODE
SOURCE_ROOT_HYPRE="$NEKCEM_SOURCE_ROOT/3rd_party/hypre"
export SOURCE_ROOT_HYPRE


function build_3rdparty() {
  printf "building 3rd-party dependencies ... "
  set -o pipefail

  cd $SOURCE_ROOT_BLAS
  ./install 2>&1 | tee -a $CASEDIR/build.log >/dev/null
  cd $CASEDIR 

  cd $SOURCE_ROOT_GSLIB
  ./install 2>&1 | tee -a $CASEDIR/build.log >/dev/null
  cd $CASEDIR

  printf "done\n"
  set +o pipefail
}

# TODO: gslib build options
MPI=1 # TODO: only default option
MPIIO=1
GSLIB_OPT+=" DESTDIR=.."
GSLIB_OPT+=" MPI=$MPI MPIIO=$MPIIO"
GSLIB_OPT+=" ADDUS=$UNDERSCORE USREXIT=0 BLAS=2"
export GSLIB_OPT


build_3rdparty

echo "========= Start configurenek ========"
# TODO: very basic...
configurenek --FC mpif77 $1 $2

echo "======== Make User file ========"
./mkuserfile

echo "========= Complete ========"
